disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - opening_brace
  - trailing_comma
  - type_name
  - cyclomatic_complexity # yeah, yeah, I know.

type_body_length:
  warning: 500
  error: 10000
function_body_length:
  warning: 200
  error: 10000
file_length:
  warning: 1000
  error: 10000
line_length:
  warning: 100
  error: 10000
function_parameter_count:
  warning: 5
  error: 10
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
